// import "./globals.css";
import { AppBar, Button, Toolbar, Typography } from "@mui/material";
import Link from "next/link";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AppBar
                    position="static"
                    sx={{ backgroundColor: "#a8d08d", marginBottom: "20px" }}
                >
                    <Toolbar
                        sx={{
                            display: "flex",
                            justifyContent: "space-between",
                        }}
                    >
                        <Typography variant="h6" component="div">
                            f88
                        </Typography>
                        <div style={{ display: "flex", gap: "50px" }}>
                            <Link
                                color="inherit"
                                href={"/"}
                                style={{ textDecoration: "none" }}
                            >
                                Trang chủ
                            </Link>
                            <Link
                                color="inherit"
                                href={"/products"}
                                style={{ textDecoration: "none" }}
                            >
                                Sản phẩm
                            </Link>
                        </div>
                        <div
                            style={{
                                width: "30px",
                                height: "30px",
                                backgroundColor: "#fff",
                                borderRadius: "50%",
                            }}
                        />
                    </Toolbar>
                </AppBar>
                {children}
            </body>
        </html>
    );
}
