import Link from "next/link";

export const metadata = {
    title: "Product page",
    description: "Generated by create next app",
};
export default function () {
    return (
        <>
            <h1>Products</h1>
            <Link href={"/products/1?name='ok'"}>Detail</Link>
        </>
    );
}
